# Generated by Django 5.1.6 on 2026-09-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_likes_thread_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
