# Generated by Django 5.1.6 on 2026-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_is_approved_reply_status_thread_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui / Tayang'), ('rejected', 'Ditolak'), ('spam', 'Terdeteksi Spam (Hidden)')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui / Tayang'), ('rejected', 'Ditolak'), ('spam', 'Terdeteksi Spam (Hidden)')], default='pending', max_length=20),
        ),
    ]
