# Generated by Django 5.2.12 on 2026-04-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Lari'), ('cycling', 'Sepeda'), ('walking', 'Jalan Kaki')], default='running', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0, help_text='Distance in kilometers', max_digits=10)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('pace', models.CharField(blank=True, help_text='Average pace (min/km)', max_length=20, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('route_data', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_time'],
            },
        ),
    ]
