# Generated by Django 5.1.6 on 2026-05-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_workoutlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
