# Generated by Django 5.2.12 on 2026-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zissubmission',
            name='month',
            field=models.CharField(default='April 2026', help_text='Periode bulan setoran (e.g. Januari 2026)', max_length=50),
            preserve_default=False,
        ),
    ]
