# Generated by Django 5.2.12 on 2026-04-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0008_product_purchase_price_product_seller_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.BooleanField(default=True, help_text='Checked in cart for checkout'),
        ),
        migrations.AddField(
            model_name='cart',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariation'),
        ),
    ]
