# Generated by Django 5.1.6 on 2026-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_mode', models.CharField(choices=[('manual', 'Kirim Bukti Transfer'), ('dynaqris', 'DynaQRIS Otomatis')], default='manual', max_length=20)),
                ('dynaqris_api_key', models.CharField(default='dq_live_623412215126097e2fe48e086a4e2d15', max_length=255)),
                ('dynaqris_qris_id', models.CharField(default='c7937a09-5a9a-49bd-a93b-e013af429995', max_length=255)),
                ('payment_timeout_minutes', models.IntegerField(default=15, help_text='Batas waktu pembayaran QRIS (menit)')),
                ('enable_anti_spam', models.BooleanField(default=True, help_text='Cegah pembuatan QRIS berulang dalam waktu singkat')),
                ('bank_name', models.CharField(default='Bank Syariah Indonesia (BSI)', max_length=100)),
                ('account_number', models.CharField(default='7260599187', max_length=100)),
                ('account_name', models.CharField(default='Barakah Economy Community', max_length=100)),
                ('manual_qris_image', models.ImageField(blank=True, null=True, upload_to='payment_settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
