# Generated by Django 5.1.6 on 2026-07-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetting',
            name='android_webhook_enabled',
            field=models.BooleanField(default=True, help_text='Aktifkan listener notifikasi bank via HP Android'),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='android_webhook_secret',
            field=models.CharField(default='barakah_android_notif_secret_123', help_text='Secret Token untuk verifikasi request webhook HP Android', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='payment_timeout_minutes',
            field=models.IntegerField(default=5, help_text='Batas waktu pembayaran QRIS (menit)'),
        ),
    ]
