# Generated by Django 5.1.6 on 2026-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsetting_android_webhook_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetting',
            name='listener_device_id',
            field=models.CharField(blank=True, help_text='ID Perangkat HP Android yang sedang aktif (Lock 1 HP)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='listener_device_name',
            field=models.CharField(blank=True, help_text='Nama / Model Perangkat HP Android aktif', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='listener_last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Timestamp terakhir heartbeat listener diterima', null=True),
        ),
    ]
