# Generated by Django 5.1.6 on 2026-08-14 20:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_products', '0009_digitalorder_paid_to_seller_directly_and_more'),
        ('orders', '0011_order_cancel_request_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dompet User / Saldo BAE',
                'verbose_name_plural': 'Dompet User / Saldo BAE',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Pengembalian Dana (Refund Pesanan Batal)'), ('PAYMENT', 'Pembayaran Belanja E-Commerce / Sinergy'), ('EARNING', 'Hasil Penjualan Produk / Kelas'), ('WITHDRAWAL', 'Penarikan Saldo BAE'), ('ADJUSTMENT', 'Penyesuaian Saldo Admin')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.userwallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='digital_products.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Mutasi Saldo BAE',
                'verbose_name_plural': 'Mutasi Saldo BAE',
                'ordering': ['-created_at'],
            },
        ),
    ]
