# Generated by Django 4.2.19 on 2025-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
