# Generated by Django 4.2.19 on 2025-03-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='collected_amount',
        ),
    ]
