# Generated by Django 4.2.19 on 2025-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
