# Generated by Django 5.1.6 on 2026-03-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(default='https://ai.sumopod.com/v1')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('system_prompt', models.TextField(default='Kamu adalah asisten pintar dari Barakah Economy.')),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.AddField(
            model_name='consultantcategory',
            name='is_ai_enabled',
            field=models.BooleanField(default=False, help_text='If True, AI will respond to messages in this category'),
        ),
    ]
