# Generated by Django 5.1.6 on 2026-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aisettings_consultantcategory_is_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantcategory',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Template pesan awal otomatis'),
        ),
    ]
