# Generated by Django 5.1.6 on 2026-03-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_consultantcategory_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_manual_mode',
            field=models.BooleanField(default=False, help_text='If True, AI will be disabled for this specific session'),
        ),
    ]
