# Generated by Django 5.1.6 on 2026-03-12 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_is_manual_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultantcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_manual_mode',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_ai_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultantcategory',
            name='ai_system_prompt',
            field=models.TextField(blank=True, help_text='Custom personality for this category. Fallback to global if empty.', null=True),
        ),
        migrations.AddField(
            model_name='consultantcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='base_url',
            field=models.URLField(blank=True, default='https://ai.sumopod.com/v1'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_consultant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultantcategory',
            name='is_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultantcategory',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.consultantcategory'),
            preserve_default=False,
        ),
    ]
