# Generated by Django 5.1.6 on 2026-03-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_consultantcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantcategory',
            name='knowledge_base',
            field=models.TextField(blank=True, default='', help_text='Materi/Modul untuk grounding AI di kategori ini (Format: Markdown/Text).'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='base_url',
            field=models.URLField(default='https://ai.sumopod.com/v1'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_consultant', to=settings.AUTH_USER_MODEL),
        ),
    ]
