# Generated by Django 5.1.6 on 2026-03-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_consultantcategory_knowledge_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Contoh: /pakar', max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Pesan yang akan dikirim saat command diklik')),
                ('icon', models.CharField(default='chat', help_text='Material icon name', max_length=50)),
                ('role', models.CharField(choices=[('public', 'Semua Pengguna'), ('expert', 'Pakar Saja'), ('admin', 'Admin Saja')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
