# Generated by Django 5.1.6 on 2026-03-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatcommand_chatsession_last_welcome_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Sesi aktif atau sudah ditutup'),
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('criticism_suggestion', models.TextField(blank=True, help_text='Kritik & Saran khusus untuk platform/admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='chat.chatsession')),
            ],
        ),
    ]
