# Generated by Django 5.1.6 on 2026-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_generalfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcommand',
            name='is_close_session',
            field=models.BooleanField(default=False, help_text='Tutup sesi otomatis'),
        ),
        migrations.AddField(
            model_name='chatcommand',
            name='is_request_review',
            field=models.BooleanField(default=False, help_text='Munculkan modal review otomatis'),
        ),
        migrations.AddField(
            model_name='chatcommand',
            name='is_toggle_ai_off',
            field=models.BooleanField(default=False, help_text='Nonaktifkan AI otomatis'),
        ),
        migrations.AddField(
            model_name='chatcommand',
            name='is_toggle_ai_on',
            field=models.BooleanField(default=False, help_text='Aktifkan AI otomatis'),
        ),
    ]
