# Generated by Django 5.1.6 on 2026-08-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatcommand_is_close_session_and_more'),
        ('orders', '0015_order_shipping_rt_rw'),
        ('products', '0018_alter_testimoni_options_testimoni_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='products.product'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('consultant', 'Konsultasi Syariah / Pakar'), ('store', 'Chat Toko / Penjual'), ('order', 'Diskusi Pesanan')], default='consultant', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Pesan Teks'), ('product_card', 'Kartu Produk'), ('order_update', 'Status Pesanan'), ('complaint', 'Pengajuan Komplain')], default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.consultantcategory'),
        ),
    ]
