# Generated by Django 5.1.6 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_featured',
        ),
    ]
