# Generated by Django 5.1.6 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_activity'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE site_content_activity DROP COLUMN IF EXISTS is_featured;",
                    reverse_sql="ALTER TABLE site_content_activity ADD COLUMN is_featured BOOLEAN DEFAULT FALSE;"
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='activity',
                    name='is_featured',
                ),
            ],
        ),
    ]
