# Generated by Django 5.1.6 on 2026-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_remove_activity_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tentang Kami', max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('partner', 'Partner'), ('mitra', 'Mitra')], default='partner', max_length=20),
        ),
    ]
