# Generated by Django 5.2.12 on 2026-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_aboutus_partner_description_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='organization_structure_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
