# Generated by Django 5.2.12 on 2026-04-14 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_header_image_full_event_thumbnail_full'),
        ('site_content', '0005_aboutus_organization_structure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.OneToOneField(blank=True, help_text='The event this documentation refers to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_documentation', to='events.event'),
        ),
    ]
