# Generated by Django 5.2.12 on 2026-04-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_activity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.CreateModel(
            name='AboutUsLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='site/legal/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='site_content.aboutus')),
            ],
        ),
    ]
