# Generated by Django 5.2.12 on 2026-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_partner_link_alter_activity_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='legal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
