# Generated by Django 5.2.12 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_aboutus_legal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
