# Generated by Django 5.2.12 on 2026-04-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0009_activity_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('hierarchy_code', models.CharField(help_text='Hierarchy numbering like 1, 1.1, 1.2, etc.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='site_content.aboutus')),
            ],
            options={
                'ordering': ['hierarchy_code', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('language', 'Website')], max_length=20)),
                ('link', models.URLField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='site_content.personnel')),
            ],
        ),
    ]
