# Generated by Django 5.2.12 on 2026-05-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0010_personnel_personnelsocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_url', models.URLField(blank=True, help_text='Link to redirect when clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
