# Generated by Django 5.2.12 on 2026-05-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='Waktu selesai tampil', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='Waktu mulai tampil', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('promotion', 'Promosi'), ('update', 'Update Terbaru'), ('announcement', 'Pengumuman'), ('info', 'Informasi'), ('other', 'Lain-lain')], default='announcement', max_length=20),
        ),
    ]
