# Generated by Django 5.1.6 on 2026-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0012_announcement_end_at_announcement_start_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='hero_banners/videos/')),
                ('target_url', models.URLField(blank=True, help_text='Link to redirect when clicked', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
