# Generated by Django 5.1.6 on 2026-05-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0013_herobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelsocialmedia',
            name='personnel',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='PersonnelSocialMedia',
        ),
    ]
