# Generated by Django 5.1.6 on 2026-05-17 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0014_remove_personnelsocialmedia_personnel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
