# Generated by Django 5.1.6

from django.db import migrations
from django.core.files.base import ContentFile
import logging

logger = logging.getLogger(__name__)

def copy_event_images_to_activities(apps, schema_editor):
    Activity = apps.get_model('site_content', 'Activity')
    for activity in Activity.objects.filter(event__isnull=False):
        # If the activity does not have a header image (is blank/empty), copy it from the event
        if not activity.header_image:
            event = activity.event
            event_image = event.header_image if event.header_image else event.thumbnail
            if event_image:
                try:
                    try:
                        event_image.open()
                    except Exception:
                        pass
                    event_image.seek(0)
                    image_name = event_image.name.split('/')[-1]
                    activity.header_image.save(
                        image_name,
                        ContentFile(event_image.read()),
                        save=True
                    )
                    logger.info(f"Successfully fixed image for activity {activity.id} ({activity.title}) from event {event.id}")
                except Exception as img_err:
                    logger.error(f"Failed to copy event image for activity {activity.id} in migration: {img_err}")

class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0016_calendarnote'),
        ('events', '0038_event_blast_completed_message_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_event_images_to_activities, reverse_code=migrations.RunPython.noop),
    ]
