# Generated by Django 5.1.6 on 2026-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0017_fix_activity_missing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
