# Generated by Django 5.1.6 on 2026-08-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0018_aboutus_contact_email_aboutus_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Aktifkan mode maintenance (perawatan sistem)')),
                ('title', models.CharField(default='Situs Sedang Dalam Pemeliharaan (Maintenance)', max_length=255)),
                ('message', models.TextField(default='Mohon maaf atas ketidaknyamanannya. Kami sedang melakukan pemeliharaan sistem untuk meningkatkan performa layanan. Silakan kembali beberapa saat lagi.')),
                ('estimated_end', models.DateTimeField(blank=True, help_text='Perkiraan waktu selesai pemeliharaan (opsional)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Maintenance',
                'verbose_name_plural': 'Pengaturan Maintenance',
            },
        ),
    ]
