# Generated by Django 5.1.6 on 2026-08-30 03:45

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0019_maintenancesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul update / apa yang baru', max_length=255)),
                ('version', models.CharField(blank=True, help_text='Versi rilis, misal: v2.4.0 (opsional)', max_length=50, null=True)),
                ('tag', models.CharField(choices=[('fitur_baru', 'Fitur Baru'), ('peningkatan', 'Peningkatan & Optimasi'), ('perbaikan', 'Perbaikan Bug'), ('pengumuman', 'Pengumuman Penting'), ('promo', 'Event & Promo')], default='fitur_baru', max_length=30)),
                ('badge_label', models.CharField(blank=True, help_text='Custom badge label (opsional)', max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Banner / foto ilustrasi', null=True, upload_to='whats_new/')),
                ('summary', models.TextField(blank=True, help_text='Ringkasan singkat untuk kartu preview', null=True)),
                ('content_type', models.CharField(choices=[('rich_text', 'Deskriptif (Rich Text / HTML)'), ('bullet_list', 'Daftar Poin (List)')], default='rich_text', max_length=20)),
                ('content_html', ckeditor.fields.RichTextField(blank=True, default='', help_text='Isi konten deskriptif / artikel lengkap')),
                ('bullet_items', models.JSONField(blank=True, default=list, help_text='Daftar poin perubahan (list array string)')),
                ('action_button_text', models.CharField(blank=True, help_text="Teks tombol aksi, misal: 'Coba Sekarang' (opsional)", max_length=100, null=True)),
                ('action_button_url', models.CharField(blank=True, help_text="Link tombol aksi, misal: '/store' (opsional)", max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Status publikasi')),
                ('is_popup_on_login', models.BooleanField(default=False, help_text='Tampilkan otomatis sebagai popup pengumuman saat user membuka aplikasi')),
                ('release_date', models.DateField(help_text='Tanggal rilis update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whats_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "What's New",
                'verbose_name_plural': "What's New",
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
