# Generated by Django 5.1.6 on 2026-08-30 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0020_whatsnew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNewFeatureSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama/ringkasan fitur atau pembaruan', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Penjelasan detail atau bullet point fitur')),
                ('category', models.CharField(choices=[('fitur_baru', 'Fitur Baru'), ('peningkatan', 'Peningkatan UI/UX'), ('keamanan', 'Keamanan & Autentikasi'), ('perbaikan', 'Perbaikan Bug'), ('sistem', 'Infrastruktur & Sistem')], default='fitur_baru', max_length=30)),
                ('is_used', models.BooleanField(default=False, help_text="Status apakah sudah pernah digunakan pada What's New")),
                ('used_in_version', models.CharField(blank=True, help_text="Keterangan rilis What's New yang memakai saran ini", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Saran Fitur What's New",
                'verbose_name_plural': "Saran Fitur What's New",
                'ordering': ['is_used', '-created_at'],
            },
        ),
    ]
