# Generated by Django 5.1.6 on 2026-09-06 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0022_seed_whats_new_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_device_id', models.CharField(blank=True, help_text='ID Perangkat GoWA yang dipilih sebagai default pengirim WhatsApp sistem', max_length=255, null=True)),
                ('default_device_name', models.CharField(blank=True, help_text='Nama akun WhatsApp pengirim default', max_length=255, null=True)),
                ('default_device_phone', models.CharField(blank=True, help_text='Nomor HP pengirim default', max_length=50, null=True)),
                ('api_url', models.CharField(default='https://bae.dailykas.com', help_text='URL GoWA Server API', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Status keaktifan gateway WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_gateway_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan WhatsApp Gateway',
                'verbose_name_plural': 'Pengaturan WhatsApp Gateway',
            },
        ),
    ]
