# Generated by Django 5.1.6 on 2026-09-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0023_whatsappgatewaysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook_url',
            field=models.CharField(blank=True, help_text='Link halaman Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='footer_tagline',
            field=models.TextField(blank=True, help_text='Deskripsi singkat profil di footer', null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='Link atau username Instagram (misal: bae.community_)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='linkedin_url',
            field=models.CharField(blank=True, help_text='Link halaman LinkedIn', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tiktok_url',
            field=models.CharField(blank=True, help_text='Link atau username TikTok', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='Link channel YouTube', max_length=255, null=True),
        ),
    ]
