# Generated by Django 5.1.6 on 2026-06-12 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_payment_method'),
        ('events', '0036_event_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='event_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charity_donations', to='events.eventregistration'),
        ),
    ]
