# Generated by Django 5.1.6 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya Layanan & Admin / Kode Unik', max_digits=12),
        ),
    ]
