# Generated by Django 5.1.6 on 2026-09-08 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_admin_fee'),
        ('products', '0018_alter_testimoni_options_testimoni_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('donation', 'Donasi Tunai'), ('waqaf', 'Waqaf Produk')], default='donation', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DonationWaqafItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waqaf_items', to='donations.donation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waqaf_donations', to='products.product')),
            ],
        ),
    ]
