# Generated by Django 5.1.6 on 2026-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0003_digitalorder_product_owner_digitalproduct_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transfer_proof',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal_proofs/'),
        ),
    ]
