# Generated by Django 5.1.6 on 2026-03-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0004_withdrawalrequest_transfer_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
