# Generated by Django 5.1.6 on 2026-03-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0005_withdrawalrequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalorder',
            name='digital_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='digital_products.digitalproduct'),
        ),
    ]
