# Generated by Django 5.2.12 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0006_alter_digitalorder_digital_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
