# Generated by Django 5.1.6 on 2026-05-15 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0007_digitalproduct_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_digital_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
