# Generated by Django 5.1.6 on 2026-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0009_digitalorder_paid_to_seller_directly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalorder',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya Layanan & Admin / Kode Unik', max_digits=12),
        ),
    ]
