# Generated by Django 5.1.6 on 2026-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0010_digitalorder_admin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_source',
            field=models.CharField(choices=[('seller_revenue', 'Hasil Jualan Toko / Digital / Kelas'), ('user_wallet', 'Saldo E-Wallet Pribadi (Profil)')], default='seller_revenue', max_length=30),
        ),
    ]
