# Generated by Django 5.1.6 on 2026-03-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_member_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User / Peminat'), ('seller', 'Seller / Penjual'), ('admin', 'Admin Barakah'), ('staff', 'Staff / Pengelola')], default='user', max_length=20),
        ),
    ]
