# Generated by Django 5.2.12 on 2026-05-04 08:26

from django.db import migrations, models

def seed_data(apps, schema_editor):
    LingkupTugas = apps.get_model('accounts', 'LingkupTugas')
    BidangTugas = apps.get_model('accounts', 'BidangTugas')

    lingkup_data = [
        {'name': 'Pusat', 'code': '1PS', 'color': 'blue'},
        {'name': 'Wilayah', 'code': '2WL', 'color': 'teal'},
        {'name': 'Daerah', 'code': '3DR', 'color': 'emerald'},
        {'name': 'Cabang', 'code': '4CB', 'color': 'indigo'},
        {'name': 'Ranting', 'code': '5RT', 'color': 'violet'},
        {'name': 'Pangkal', 'code': '6PK', 'color': 'purple'},
    ]
    for data in lingkup_data:
        LingkupTugas.objects.get_or_create(code=data['code'], defaults=data)

    bidang_data = [
        {'name': 'Manajemen Umum', 'code': 'MNG', 'color': 'blue'},
        {'name': 'Sumber Daya Manusia', 'code': 'SDM', 'color': 'emerald'},
        {'name': 'Ekonomi Bisnis', 'code': 'EKB', 'color': 'amber'},
        {'name': 'Olahraga dan Kepemudaan', 'code': 'ORP', 'color': 'red'},
    ]
    for data in bidang_data:
        BidangTugas.objects.get_or_create(code=data['code'], defaults=data)

def reverse_seed_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_userlabel_user_custom_roles_user_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='emerald', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LingkupTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Jabatan di BAE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bidang_tugas',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.bidangtugas'),
        ),
        migrations.AddField(
            model_name='user',
            name='lingkup_tugas',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.lingkuptugas'),
        ),
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
