# Generated by Django 5.2.12 on 2026-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_attendance_json',
            field=models.JSONField(blank=True, default=list, help_text='Cached list of attended events'),
        ),
    ]
