# Generated by Django 5.1.6 on 2026-05-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_event_attendance_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_automatic',
            field=models.BooleanField(default=True, help_text='If True, this role can be obtained automatically via profile completion.'),
        ),
    ]
