# Generated by Django 5.1.6 on 2026-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_is_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(blank=True, default=0, help_text='Tingkatan role untuk hierarki/rumus'),
        ),
        migrations.AddField(
            model_name='user',
            name='jenjang_kesiapan',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('1+', '1+'), ('2', '2'), ('2+', '2+'), ('3', '3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jenjang_pemahaman',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1J', '1J'), ('2A', '2A'), ('2B', '2B'), ('PI', 'PI'), ('PF', 'PF'), ('MPT', 'MPT')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kelas_academy',
            field=models.CharField(blank=True, choices=[('PRA', 'PRA'), ('A1-1', 'A1-1'), ('A1-2', 'A1-2'), ('A1-3', 'A1-3'), ('A2-1', 'A2-1'), ('A2-2', 'A2-2'), ('A2-3', 'A2-3'), ('A2P', 'A2P')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tugas_fungsi',
            field=models.CharField(blank=True, choices=[('UP SR', 'UP SR'), ('KASI', 'KASI'), ('UP RM', 'UP RM'), ('KAUR', 'KAUR'), ('AK', 'AK'), ('MPT', 'MPT'), ('MK', 'MK')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlabel',
            name='level',
            field=models.IntegerField(blank=True, default=0, help_text='Tingkatan label untuk rumus/filter'),
        ),
    ]
