# Generated by Django 5.1.6 on 2026-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_level_and_kaderisasi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Keterangan tambahan kaderisasi', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rombel',
            field=models.CharField(blank=True, help_text='Nama rombongan belajar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tgl_alih_jenjang',
            field=models.DateField(blank=True, help_text='Tanggal alih jenjang terakhir', null=True),
        ),
    ]
