# Generated by Django 5.1.6 on 2026-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_rombel_tgl_alih_jenjang_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sadar_donasi',
            field=models.CharField(blank=True, choices=[('WI', 'WI'), ('WZU', 'WZU'), ('WZK', 'WZK'), ('W5P', 'W5P')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jenjang_kesiapan',
            field=models.CharField(blank=True, choices=[('RELAWAN', 'RELAWAN'), ('MUDA', 'MUDA'), ('MUDA+', 'MUDA+'), ('MADYA', 'MADYA'), ('MADYA+', 'MADYA+'), ('UTAMA', 'UTAMA')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jenjang_pemahaman',
            field=models.CharField(blank=True, choices=[('PRA', 'PRA'), ('MUDA', 'MUDA'), ('MADYA', 'MADYA'), ('UTAMA', 'UTAMA'), ('PETUGAS', 'PETUGAS'), ('PENGURUS', 'PENGURUS'), ('IBU IBU', 'IBU IBU')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kelas_academy',
            field=models.CharField(blank=True, choices=[('PRA', 'PRA'), ('MUDA-1', 'MUDA-1'), ('MUDA-2', 'MUDA-2'), ('MUDA-3', 'MUDA-3'), ('MADYA-1', 'MADYA-1'), ('MADYA-2', 'MADYA-2'), ('MADYA-3', 'MADYA-3'), ('MADYA-P', 'MADYA-P')], max_length=10, null=True),
        ),
    ]
