# Generated by Django 5.1.6 on 2026-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_sadar_donasi_alter_user_jenjang_kesiapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_agreement_accepted',
            field=models.BooleanField(default=False, help_text='Tandai jika user telah menyetujui user agreement'),
        ),
    ]
