# Generated by Django 5.1.6 on 2026-06-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_user_agreement_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lembar Kesepakatan & Ketentuan Data', max_length=255)),
                ('subtitle', models.CharField(default='Komitmen Keamanan & Privasi Barakah Economy Community', max_length=255)),
                ('content', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Agreement',
                'verbose_name_plural': 'User Agreement',
            },
        ),
    ]
