# Generated by Django 5.1.6 on 2026-08-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_increase_phone_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=120)),
                ('device_name', models.CharField(default='Unknown Device', help_text='e.g. Chrome di Windows Desktop, Safari di iPhone', max_length=150)),
                ('device_type', models.CharField(default='desktop', help_text='desktop, mobile, tablet', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
