# Generated by Django 5.1.6 on 2026-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userdevicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicesession',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Perangkat diblokir jika user mengklik Bukan Saya'),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='location_country',
            field=models.CharField(blank=True, default='Indonesia', max_length=100),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='location_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='security_token',
            field=models.CharField(blank=True, help_text='Token verifikasi keamanan untuk konfirmasi/blokir', max_length=64, null=True, unique=True),
        ),
    ]
