# Generated by Django 5.1.6 on 2026-09-24 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userdevicesession_is_blocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBlastSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('campaign_source', models.CharField(default='custom_broadcast', help_text='custom_broadcast, event, meeting, users', max_length=50)),
                ('message_template', models.TextField()),
                ('has_image', models.BooleanField(default=False)),
                ('image_filename', models.CharField(blank=True, default='', max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_blast_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBlastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='accounts.whatsappblastsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
