# Generated by Django 5.1.6 on 2026-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_whatsappblastsession_whatsappblastrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappblastsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappblastsession',
            name='scheduled_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
