# Generated by Django 5.1.6 on 2026-06-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsettings',
            name='latency_mode',
            field=models.CharField(choices=[('low', 'Low Latency'), ('standard', 'Standard Latency')], default='low', max_length=20),
        ),
    ]
