# Generated by Django 5.1.6 on 2026-06-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_streamingsettings_latency_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsettings',
            name='save_recording',
            field=models.BooleanField(default=True),
        ),
    ]
