# Generated by Django 5.1.6 on 2026-06-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_streamingsettings_save_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsettings',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='live_thumbnails/'),
        ),
    ]
