# Generated by Django 5.1.6 on 2026-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_streamingsettings_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
