# Generated by Django 5.1.6 on 2026-06-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_streamingviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsettings',
            name='is_hp_streaming_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamingsettings',
            name='whip_hls_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
