# Generated by Django 5.1.6 on 2026-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_add_hp_streaming_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsettings',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=15),
        ),
    ]
