# Generated by Django 5.1.6 on 2026-06-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_auto_post_to_activity'),
        ('streaming', '0007_streamingsettings_orientation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStreamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='streaminglike',
            name='unique_user_like',
        ),
        migrations.AddField(
            model_name='streamingchat',
            name='stream_key',
            field=models.CharField(default='barakah_stream_key', max_length=100),
        ),
        migrations.AddField(
            model_name='streaminglike',
            name='stream_key',
            field=models.CharField(default='barakah_stream_key', max_length=100),
        ),
        migrations.AddField(
            model_name='streamingsettings',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='events.event'),
        ),
        migrations.AddField(
            model_name='streamingsettings',
            name='require_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamingviewer',
            name='stream_key',
            field=models.CharField(default='barakah_stream_key', max_length=100),
        ),
        migrations.AlterField(
            model_name='streamingviewer',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='streaminglike',
            constraint=models.UniqueConstraint(fields=('user', 'stream_key'), name='unique_user_stream_like'),
        ),
        migrations.AddConstraint(
            model_name='streamingviewer',
            constraint=models.UniqueConstraint(fields=('session_key', 'stream_key'), name='unique_session_stream_viewer'),
        ),
        migrations.AddField(
            model_name='eventstreamnotification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_notifications', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventstreamnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventstreamnotification',
            name='stream_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='streaming.streamingsettings'),
        ),
    ]
