# Generated by Django 5.2.12 on 2026-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_grand_total_order_seller_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qris_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qrisly_history_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resi_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
