# Generated by Django 5.2.12 on 2026-04-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_qris_payload_order_qrisly_history_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='resi_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
