# Generated by Django 5.2.12 on 2026-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_proof_order_resi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_note',
            field=models.TextField(blank=True, help_text='Catatan pembeli untuk penjual', null=True),
        ),
    ]
