# Generated by Django 5.1.6 on 2026-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_auto_complete_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_to_seller_directly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_bank_holder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_qris_orders/'),
        ),
    ]
