# Generated by Django 5.1.6 on 2026-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_paid_to_seller_directly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complaint_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complaint_reason',
            field=models.TextField(blank=True, help_text='Alasan komplain / banding dari pembeli', null=True),
        ),
    ]
