# Generated by Django 5.1.6 on 2026-08-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_recipient_name_order_recipient_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_request_reason',
            field=models.TextField(blank=True, help_text='Alasan permohonan pembatalan/diskusi dari pembeli', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Menunggu Persetujuan Penjual'), ('approved', 'Disetujui Penjual'), ('rejected', 'Ditolak Penjual')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='used_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jumlah Saldo BAE yang digunakan', max_digits=12),
        ),
    ]
