# Generated by Django 5.1.6 on 2026-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cancel_request_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya Layanan & Admin / Kode Unik', max_digits=12),
        ),
    ]
