# Generated by Django 5.1.6 on 2026-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_admin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Nama kurir / pengirim jika kirim sendiri', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, help_text='No telp / WA pengirim jika kirim sendiri', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('ekspedisi', 'Ekspedisi / Kurir Logistik'), ('kurir_toko', 'Kirim Sendiri / Kurir Toko')], default='ekspedisi', max_length=50, null=True),
        ),
    ]
