# Generated by Django 5.1.6 on 2026-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_driver_name_order_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total nominal uang tunai yang harus disiapkan pembeli (COD produk / ongkir ekspedisi COD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Tanggal rencana pengiriman kurir toko', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(blank=True, help_text='Slot jam pengantaran: 08:00 - 12:00, 12:00 - 15:00, 15:00 - 18:00, 18:00 - 21:00', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_schedule_type',
            field=models.CharField(blank=True, default='days', help_text='Mode jadwal pengantaran: days / slot / instant', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.IntegerField(default=3),
        ),
    ]
