# Generated by Django 5.1.6 on 2026-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_cod_amount_to_pay_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_rt_rw',
            field=models.CharField(blank=True, help_text='RT/RW', max_length=20, null=True),
        ),
    ]
