# Generated by Django 5.1.6 on 2026-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_storecourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_timing_choice',
            field=models.CharField(blank=True, default='current_schedule', help_text='Pilihan jadwal pengiriman: current_schedule (Ikut Jadwal Saat Ini/Minggu Ini) atau next_week (Kirim Minggu Depan)', max_length=50, null=True),
        ),
    ]
