# Generated by Django 5.1.6 on 2026-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_delivery_timing_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_distance_based_shipping',
            field=models.BooleanField(default=False, help_text='Apakah ongkir pesanan ini dihitung sesuai jarak (dikonfirmasi seller/kurir kemudian)'),
        ),
    ]
