# Generated by Django 5.1.6 on 2026-03-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('beneficiaries', models.JSONField(default=list, help_text='List of beneficiaries with status')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='campaigns.campaign')),
            ],
        ),
    ]
