# Generated by Django 5.1.6 on 2026-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignrealization'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='campaignrealization',
                    name='beneficiary_status',
                    field=models.CharField(choices=[('Fakir', 'Fakir'), ('Miskin', 'Miskin'), ('Amil', 'Amil'), ('Mualaf', 'Mualaf'), ('Riqab', 'Riqab'), ('Gharimin', 'Gharimin'), ('Fisabilillah', 'Fisabilillah'), ('Ibnu Sabil', 'Ibnu Sabil'), ('Yatim', 'Yatim'), ('Operational', 'Operational'), ('Bencana Alam', 'Bencana Alam'), ('Kemanusiaan', 'Kemanusiaan'), ('Kesehatan', 'Kesehatan'), ('Pendidikan', 'Pendidikan'), ('Lingkungan', 'Lingkungan'), ('Pembangunan', 'Pembangunan'), ('Sosial', 'Sosial'), ('Masjid', 'Masjid'), ('Waqaf', 'Waqaf'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50),
                ),
                migrations.AlterField(
                    model_name='campaignrealization',
                    name='beneficiaries',
                    field=models.TextField(help_text='List penerima manfaat'),
                ),
            ]
        ),
    ]
