# Generated by Django 5.2.12 on 2026-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_approval_status_campaign_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
