# Generated by Django 5.2.12 on 2026-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('infak', 'Infak Barakah'), ('sedekah', 'Sedekah Barakah'), ('zakat', 'Zakat Barakah'), ('donasi', 'Donasi Barakah'), ('bencana', 'Bantuan Bencana Alam'), ('kemanusiaan', 'Bantuan Kemanusiaan'), ('kesehatan', 'Bantuan Kesehatan'), ('lingkungan', 'Bantuan Lingkungan'), ('pembangunan', 'Bantuan Pembangunan'), ('sosial', 'Bantuan Sosial'), ('duafa', 'Bantuan Duafa'), ('lainnya', 'Lainnya')], max_length=20),
        ),
    ]
