# Generated by Django 5.1.6 on 2026-05-15 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
