# Generated by Django 5.1.6 on 2026-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_likes'),
        ('products', '0018_alter_testimoni_options_testimoni_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collab_products',
            field=models.ManyToManyField(blank=True, related_name='collab_campaigns', to='products.product'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='collaboration_type',
            field=models.CharField(blank=True, choices=[('none', 'Tidak Ada Kolaborasi'), ('donasi', 'Kolaborasi Donasi'), ('waqaf', 'Kolaborasi Waqaf Produk')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_collaboration',
            field=models.BooleanField(default=False),
        ),
    ]
