# Generated by Django 5.2.12 on 2026-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courseenrollment_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
