# Generated by Django 5.2.12 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_courseenrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
