# Generated by Django 5.2.12 on 2026-04-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_courseenrollment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='courses/certificates/templates/')),
                ('name_x', models.FloatField(default=10.0)),
                ('name_y', models.FloatField(default=45.0)),
                ('name_width', models.FloatField(default=80.0)),
                ('name_height', models.FloatField(default=10.0)),
                ('font_size', models.IntegerField(default=60)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('font_family', models.CharField(default='Roboto-Bold.ttf', max_length=100)),
                ('font_bold', models.BooleanField(default=True)),
                ('font_italic', models.BooleanField(default=False)),
                ('text_align', models.CharField(default='center', max_length=10)),
                ('vertical_align', models.CharField(default='middle', max_length=10)),
                ('show_unique_code', models.BooleanField(default=False)),
                ('code_x', models.FloatField(default=10.0)),
                ('code_y', models.FloatField(default=90.0)),
                ('code_font_size', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_design', to='courses.course')),
            ],
        ),
    ]
