# Generated by Django 5.2.12 on 2026-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_coursecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='code_font_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='code_font_family',
            field=models.CharField(default='Roboto-Bold.ttf', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='code_font_size',
            field=models.IntegerField(default=14),
        ),
    ]
