# Generated by Django 5.2.12 on 2026-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursecertificate_code_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='date_font_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='date_font_family',
            field=models.CharField(default='Roboto-Bold.ttf', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='date_font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='date_x',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='date_y',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
    ]
