# Generated by Django 5.2.12 on 2026-05-06 08:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_coursecertificate_date_font_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='content_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video (YouTube)'), ('text', 'Penjabaran Materi (Teks/Gambar)'), ('quiz', 'Kuis (Pilihan Ganda)')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text='Store questions, options, and settings', null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary or instructions', null=True),
        ),
    ]
