# Generated by Django 5.2.12 on 2026-05-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_options_coursematerial_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
