# Generated by Django 5.1.6 on 2026-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_coursematerial_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='quiz_answers',
            field=models.JSONField(blank=True, help_text="Store student's answers for quiz", null=True),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
