# Generated by Django 5.1.6 on 2026-03-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_shop_description_profile_shop_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_decoration',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_font',
            field=models.CharField(blank=True, default='sans', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_layout',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_theme_color',
            field=models.CharField(blank=True, default='green', max_length=50),
        ),
    ]
