# Generated by Django 5.1.6 on 2026-03-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_shop_decoration_profile_shop_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_template',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
