# Generated by Django 5.2.12 on 2026-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_shop_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ktp_image',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan (NIK) dari KTP', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_header_style',
            field=models.CharField(blank=True, default='theme', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
    ]
