# Generated by Django 5.1.6 on 2026-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_shop_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Status verifikasi member berdasarkan KTP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan (NIK) dari KTP', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_header_style',
            field=models.CharField(blank=True, default='theme', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
    ]
