# Generated by Django 5.2.12 on 2026-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_ktp_image_profile_nik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_city_id',
            field=models.CharField(blank=True, help_text='Expedition City ID', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_province_id',
            field=models.CharField(blank=True, help_text='Expedition Province ID', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_subdistrict_id',
            field=models.CharField(blank=True, help_text='Expedition Subdistrict ID', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_subdistrict_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]

