# Generated by Django 5.2.12 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_address_city_id_profile_address_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_village_id',
            field=models.CharField(blank=True, help_text='Expedition Village ID', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_supported_couriers',
            field=models.CharField(blank=True, default='jne,pos,tiki,jnt', help_text='Comma separated active courier codes', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_city_id',
            field=models.CharField(blank=True, help_text='Expedition City ID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_province_id',
            field=models.CharField(blank=True, help_text='Expedition Province ID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_subdistrict_id',
            field=models.CharField(blank=True, help_text='Expedition Subdistrict ID', max_length=10, null=True),
        ),
    ]
