# Generated by Django 5.2.12 on 2026-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_village_name',
            field=models.CharField(blank=True, help_text='Nama Kelurahan/Desa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_picture_url',
            field=models.URLField(blank=True, help_text='URL foto profil dari Google OAuth', max_length=500, null=True),
        ),
    ]
