# Generated by Django 5.2.12 on 2026-04-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_add_google_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
