# Generated by Django 5.2.12 on 2026-05-04 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_address_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study_finish_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('community_username', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(max_length=15)),
                ('brand_name', models.CharField(max_length=100)),
                ('business_field', models.CharField(choices=[('kuliner', 'Kuliner'), ('fashion', 'Fashion'), ('jasa', 'Jasa'), ('digital', 'Digital'), ('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('lainnya', 'Lainnya')], max_length=20)),
                ('business_field_other', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Maks. 150 kata')),
                ('main_products', models.TextField()),
                ('business_scale', models.CharField(choices=[('<1jt', '< Rp1 juta'), ('1-5jt', 'Rp1 – 5 juta'), ('5-10jt', 'Rp5 – 10 juta'), ('10-25jt', 'Rp10 – 25 juta'), ('25-50jt', 'Rp25 – 50 juta'), ('50-100jt', 'Rp50 – 100 juta'), ('100-250jt', 'Rp100 – 250 juta'), ('>250jt', '> Rp250 juta')], max_length=20)),
                ('keunggulan', models.TextField(help_text='Maks. 100 kata')),
                ('target_market', models.TextField()),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_contact', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='business_logos/')),
                ('foto_produk_1', models.ImageField(upload_to='business_products/')),
                ('foto_produk_2', models.ImageField(blank=True, null=True, upload_to='business_products/')),
                ('foto_produk_3', models.ImageField(blank=True, null=True, upload_to='business_products/')),
                ('business_status', models.CharField(choices=[('baru', 'Baru mulai'), ('berjalan', 'Sudah berjalan'), ('stabil', 'Sudah stabil')], max_length=20)),
                ('sales_area', models.CharField(choices=[('lokal', 'Lokal'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=20)),
                ('readiness_order', models.CharField(choices=[('siap', 'Siap'), ('belum_siap', 'Belum siap')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_description', models.TextField(help_text='Maks. 100 kata')),
                ('display_contact', models.CharField(max_length=255)),
                ('is_website_display_approved', models.BooleanField(default=False)),
                ('business_needs', models.JSONField(blank=True, default=list)),
                ('business_needs_other', models.CharField(blank=True, max_length=100, null=True)),
                ('expectations', models.TextField(blank=True, null=True)),
                ('is_curated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
