# Generated by Django 5.2.12 on 2026-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_study_finish_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('Rendah', 'Jarang Olahraga'), ('Sedang', '1-3x Seminggu'), ('Tinggi', 'Setiap Hari')], default='Sedang', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_fitness',
            field=models.IntegerField(blank=True, help_text='Age for fitness analysis', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_target',
            field=models.FloatField(default=5.0, help_text='Daily distance target in KM'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in CM', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='starting_weight',
            field=models.FloatField(blank=True, help_text='Weight when joined', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Current weight in KG', null=True),
        ),
    ]
