# Generated by Django 5.1.6 on 2026-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info_source',
            field=models.CharField(blank=True, choices=[('sosmed', 'Sosial Media (Instagram/FB/TikTok)'), ('wa', 'WhatsApp Group / Chat'), ('teman', 'Teman / Keluarga'), ('iklan', 'Iklan'), ('website', 'Website / Google'), ('event', 'Event / Acara'), ('lainnya', 'Lainnya')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Nama orang yang mengajak', max_length=100, null=True),
        ),
    ]
