# Generated by Django 5.1.6 on 2026-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_info_source_profile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('kepercayaan', 'Kepercayaan YME / Lainnya')], max_length=20, null=True),
        ),
    ]
