# Generated by Django 5.1.6 on 2026-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_profile_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
