# Generated by Django 5.1.6 on 2026-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profile_agama'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_change_count',
            field=models.IntegerField(default=0),
        ),
    ]
