# Generated by Django 5.1.6 on 2026-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_rt_rw',
            field=models.CharField(blank=True, help_text='RT/RW e.g. 003/005', max_length=20, null=True),
        ),
    ]
