# Generated by Django 5.1.6 on 2026-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_shop_name_shoplike_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_delivery_timing_choice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_range_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_range_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delivery_schedule_type',
            field=models.CharField(blank=True, choices=[('range', 'Rentang Hari'), ('days', 'Hari Tertentu'), ('date', 'Tanggal Spesifik')], default='range', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_delivery_schedule_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_operational_hours_active',
            field=models.BooleanField(default=False, help_text='Aktifkan jam operasional toko secara global'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Aktifkan default Pre-Order (PO) toko'),
        ),
        migrations.AddField(
            model_name='profile',
            name='operational_hours',
            field=models.CharField(blank=True, help_text='Contoh: Setiap Hari (08:00 - 21:00 WIB)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='out_of_po_shipping_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='out_of_po_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='out_of_po_shipping_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Ongkir'), ('distance', 'Sesuai Jarak')], default='flat', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preorder_days',
            field=models.CharField(blank=True, help_text="Hari PO default, misal: 'Senin, Rabu, Jumat'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preorder_days_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preorder_days_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preorder_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preorder_type',
            field=models.CharField(blank=True, choices=[('days', 'Hari Tertentu'), ('range', 'Rentang Hari')], default='days', max_length=20, null=True),
        ),
    ]
