# Generated by Django 5.1.6 on 2026-09-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profile_allow_delivery_timing_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_sold_count',
            field=models.BooleanField(default=True, help_text='Tampilkan jumlah terjual produk toko di etalase dan detail produk'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_delivery_timing_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(blank=True, db_index=True, help_text='Nama toko unik untuk URL /store/{nama_toko}', max_length=150, null=True, unique=True),
        ),
    ]
