# Generated by Django 5.1.6 on 2026-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_sessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
