# Generated by Django 5.1.6 on 2026-05-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingsession_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Belum Konfirmasi'), ('attending', 'Akan Hadir'), ('not_attending', 'Tidak Hadir')], default='pending', max_length=20),
        ),
    ]
