# Generated by Django 5.2.12 on 2026-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_purchase_price_product_seller_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supported_couriers',
            field=models.CharField(blank=True, default='jne,pos,tiki,jnt', help_text='Comma separated active courier codes for this product', max_length=255),
        ),
    ]
