# Generated by Django 5.2.12 on 2026-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
