# Generated by Django 5.2.12 on 2026-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cod_available',
            field=models.BooleanField(default=False, help_text='Apakah produk ini mendukung COD'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_instructions',
            field=models.TextField(blank=True, help_text='Informasi khusus pengambilan atau teknis setelah pembelian', null=True),
        ),
    ]
