# Generated by Django 5.1.6 on 2026-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='own_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='own_bank_holder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='own_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='own_bank_status',
            field=models.CharField(choices=[('none', 'Tidak Menggunakan'), ('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='own_qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_qris/'),
        ),
    ]
