# Generated by Django 5.1.6 on 2026-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs / buah'), ('buku', 'buku / eksemplar'), ('eksemplar', 'eksemplar'), ('lembar', 'lembar'), ('jilid', 'jilid'), ('kg', 'kg (Kilogram)'), ('gram', 'gram (g)'), ('ons', 'ons'), ('liter', 'liter (L)'), ('ml', 'mililiter (ml)'), ('pack', 'pack / bungkus'), ('box', 'box / kotak'), ('dus', 'dus / karton'), ('botol', 'botol'), ('sachet', 'sachet'), ('kaleng', 'kaleng'), ('pasang', 'pasang'), ('set', 'set'), ('unit', 'unit'), ('porsi', 'porsi'), ('lusin', 'lusin (12 pcs)'), ('kodi', 'kodi (20 pcs)'), ('meter', 'meter (m)'), ('paket', 'paket')], default='pcs', max_length=20),
        ),
    ]
