# Generated by Django 5.1.6 on 2026-08-17 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_update_product_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimoni',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testimoni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_testimonies/'),
        ),
        migrations.AddField(
            model_name='testimoni',
            name='is_admin_entry',
            field=models.BooleanField(default=False, help_text='Diinput secara manual oleh admin'),
        ),
        migrations.AddField(
            model_name='testimoni',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_testimonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama Promo / Kampanye', max_length=150)),
                ('discount_type', models.CharField(choices=[('percentage', 'Diskon Persentase (%)'), ('nominal', 'Potongan Tetap (Rp)'), ('min_qty_discount', 'Diskon Grosir (Beli >= X Qty)')], default='percentage', max_length=30)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Nilai Diskon (% atau Rp)', max_digits=12)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimal jumlah beli untuk promo grosir')),
                ('is_min_qty_percentage', models.BooleanField(default=True, help_text='Jika grosir, nilai diskon berupa % (True) atau Rp (False)')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
