# Generated by Django 5.1.6 on 2026-09-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_testimoni_options_testimoni_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shipping_cost_active',
            field=models.BooleanField(default=False, help_text='Aktifkan ongkos kirim flat untuk produk ini'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nominal ongkos kirim produk', max_digits=12),
        ),
    ]
