# Generated by Django 5.1.6 on 2026-09-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_is_shipping_cost_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='can_edit_by_admin',
            field=models.BooleanField(default=False, help_text='Akses edit dibuka / direset khusus oleh admin'),
        ),
        migrations.AddField(
            model_name='testimoni',
            name='edit_count',
            field=models.IntegerField(default=0, help_text='Jumlah kali ulasan telah diedit oleh pembeli (maksimal 1x)'),
        ),
        migrations.AddField(
            model_name='testimoni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
