# Generated by Django 5.1.6 on 2026-09-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_testimoni_can_edit_by_admin_testimoni_edit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_sold_count',
            field=models.IntegerField(default=0, help_text='Jumlah terjual tambahan / penyesuaian manual oleh admin'),
        ),
    ]
