# Generated by Django 5.1.6 on 2026-09-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_manual_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Tanggal pengantaran spesifik', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(blank=True, help_text="Hari pengantaran, misal: 'Senin, Rabu, Jumat'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_note',
            field=models.CharField(blank=True, help_text="Catatan pengantaran, misal: 'Pengiriman mulai pukul 10:00 WIB'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_range_max',
            field=models.PositiveIntegerField(blank=True, help_text='Estimasi pengantaran max hari', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_range_min',
            field=models.PositiveIntegerField(blank=True, help_text='Estimasi pengantaran min hari', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_schedule_type',
            field=models.CharField(blank=True, choices=[('range', 'Rentang Hari'), ('days', 'Hari Tertentu'), ('date', 'Tanggal Spesifik')], default='range', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_delivery_schedule_active',
            field=models.BooleanField(default=False, help_text='Aktifkan jadwal / tanggal pengantaran'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_operational_hours_active',
            field=models.BooleanField(default=False, help_text='Aktifkan jam operasional toko untuk produk ini'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Aktifkan sistem Pre-Order (PO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='operational_hours',
            field=models.CharField(blank=True, help_text='Contoh: Senin - Sabtu, 08:00 - 17:00 WIB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_days_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maksimal hari PO', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_days_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimal hari PO', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_duration',
            field=models.CharField(blank=True, help_text='Label rentang hari PO, contoh: 3 - 7 Hari', max_length=100, null=True),
        ),
    ]
