# Generated by Django 5.1.6 on 2026-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_delivery_date_product_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_delivery_timing_choice',
            field=models.BooleanField(default=True, help_text='Izinkan pembeli memilih pengiriman minggu ini atau minggu depannya'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_po_shipping_active',
            field=models.BooleanField(default=False, help_text='Aktifkan ongkir flat seller / luar jam PO (tetap flat walau beli banyak produk)'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_po_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nominal ongkos kirim flat di luar jam PO', max_digits=12),
        ),
    ]
