# Generated by Django 5.1.6 on 2026-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_allow_delivery_timing_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_days',
            field=models.CharField(blank=True, help_text="Hari PO, misal: 'Senin, Rabu, Jumat'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_type',
            field=models.CharField(blank=True, choices=[('days', 'Hari Tertentu'), ('range', 'Rentang Hari')], default='days', help_text='Tipe PO: days (hari tertentu) atau range (rentang hari)', max_length=20, null=True),
        ),
    ]
