# Generated by Django 5.1.6 on 2026-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_preorder_days_product_preorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_po_shipping_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Ongkir'), ('distance', 'Sesuai Jarak')], default='flat', help_text='Tipe ongkir luar jam PO: flat atau distance (sesuai jarak)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Ongkir'), ('distance', 'Sesuai Jarak')], default='flat', help_text='Tipe ongkos kirim: flat atau distance (sesuai jarak)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_shipping_cost_active',
            field=models.BooleanField(default=False, help_text='Aktifkan ongkos kirim toko untuk produk ini'),
        ),
        migrations.AlterField(
            model_name='product',
            name='out_of_po_shipping_active',
            field=models.BooleanField(default=False, help_text='Aktifkan ongkir seller / luar jam PO'),
        ),
    ]
