# Generated by Django 5.1.6 on 2026-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_out_of_po_shipping_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_store_operational_settings',
            field=models.BooleanField(default=True, help_text='Jika True, mengikuti pengaturan global toko. Jika False, menggunakan pengaturan custom di bawah.'),
        ),
    ]
