# Generated by Django 5.1.6 on 2026-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_use_store_operational_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allow_delivery_timing_choice',
            field=models.BooleanField(default=False, help_text='Izinkan pembeli memilih pengiriman minggu ini atau minggu depannya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs / buah'), ('buku', 'buku / eksemplar'), ('eksemplar', 'eksemplar'), ('lembar', 'lembar'), ('jilid', 'jilid'), ('kg', 'kg (Kilogram)'), ('gram', 'gram (g)'), ('50 gram', '50 gram'), ('100 gram', '100 gram'), ('200 gram', '200 gram'), ('250 gram', '250 gram'), ('500 gram', '500 gram'), ('ons', 'ons'), ('ikat', 'ikat'), ('liter', 'liter (L)'), ('ml', 'mililiter (ml)'), ('pack', 'pack / bungkus'), ('box', 'box / kotak'), ('dus', 'dus / karton'), ('botol', 'botol'), ('sachet', 'sachet'), ('kaleng', 'kaleng'), ('pasang', 'pasang'), ('set', 'set'), ('unit', 'unit'), ('porsi', 'porsi'), ('lusin', 'lusin (12 pcs)'), ('kodi', 'kodi (20 pcs)'), ('meter', 'meter (m)'), ('paket', 'paket')], default='pcs', max_length=20),
        ),
    ]
