# Generated by Django 5.2.12 on 2026-04-07 04:39

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='events/headers/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_contact', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
