# Generated by Django 5.2.12 on 2026-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventformfield_eventregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
