# Generated by Django 5.2.12 on 2026-04-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='documentation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='price_type',
            field=models.CharField(choices=[('free', 'Gratis'), ('fixed', 'Berbayar (Fix)'), ('voluntary', 'Sukarela (Seikhlasnya)'), ('hybrid_1', 'Hybrid 1 (Min Fix + Topup)'), ('hybrid_2', 'Hybrid 2 (Pilihan Fix/Sukarela)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='events/payments/'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EventDocumentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/documentation/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_images', to='events.event')),
            ],
        ),
    ]
