# Generated by Django 5.2.12 on 2026-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header_image_full',
            field=models.ImageField(blank=True, null=True, upload_to='events/headers/full/'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_full',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/full/'),
        ),
    ]
