# Generated by Django 5.2.12 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_header_image_full_event_thumbnail_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
