# Generated by Django 5.2.12 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attended_at',
            field=models.DateTimeField(blank=True, help_text='Waktu scan kehadiran', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_attended',
            field=models.BooleanField(default=False, help_text='Tandai hadir saat event berlangsung'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='unique_code',
            field=models.CharField(blank=True, help_text='Kode unik untuk QR Code kehadiran', max_length=20, null=True, unique=True),
        ),
    ]
