# Generated by Django 5.2.12 on 2026-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_qr_attendance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='ocr_data',
            field=models.JSONField(blank=True, help_text='Data hasil ekstraksi OCR AI', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ocr_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='QR Code yang di-generate server', null=True, upload_to='events/qr_codes/'),
        ),
    ]
