# Generated by Django 5.2.12 on 2026-04-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventregistration_ocr_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='Lampiran berkas pendukung (PDF/Gambar/Dokumen)', null=True, upload_to='events/attachments/'),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_file_title',
            field=models.CharField(blank=True, help_text='Judul untuk berkas (misal: Daftar Menu)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_link',
            field=models.URLField(blank=True, help_text='Link tautan eksternal pendukung', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_link_title',
            field=models.CharField(blank=True, help_text='Judul untuk link (misal: Lokasi Gmaps)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, help_text='Kapasitas terbatas jika > 0, tak terbatas jika 0.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='documentation_frame_1_1',
            field=models.ImageField(blank=True, help_text='Bingkai 1:1 format transparan (PNG) untuk otomatis overlay dokumentasi.', null=True, upload_to='events/frames/'),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_do',
            field=models.TextField(blank=True, help_text='Baris baru memisahkan tiap point Do', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_dont',
            field=models.TextField(blank=True, help_text='Baris baru memisahkan tiap point Dont', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Umum (Tampil di Beranda)'), ('private', 'Privat (Hanya lewat link langsung)')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Misal: Sesi 1 - Pembukaan', max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, help_text='Misal: Pemateri Ahli', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/speakers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.eventregistration')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.eventsession')),
            ],
            options={
                'unique_together': {('registration', 'session')},
            },
        ),
    ]
