# Generated by Django 5.2.12 on 2026-04-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_attachment_file_event_attachment_file_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(upload_to='events/certificates/templates/')),
                ('name_x', models.FloatField(default=50.0)),
                ('name_y', models.FloatField(default=50.0)),
                ('font_size', models.IntegerField(default=40)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(default='Roboto-Bold.ttf', max_length=100)),
                ('show_unique_code', models.BooleanField(default=False)),
                ('code_x', models.FloatField(default=10.0)),
                ('code_y', models.FloatField(default=90.0)),
                ('code_font_size', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.event')),
            ],
        ),
    ]
