# Generated by Django 5.2.12 on 2026-04-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='name_height',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='name_width',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='text_align',
            field=models.CharField(default='center', max_length=20),
        ),
    ]
