# Generated by Django 5.2.12 on 2026-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventcertificate_name_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='font_bold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='font_italic',
            field=models.BooleanField(default=False),
        ),
    ]
