# Generated by Django 5.2.12 on 2026-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventcertificate_font_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='vertical_align',
            field=models.CharField(default='middle', max_length=10),
        ),
    ]
