# Generated by Django 5.2.12 on 2026-04-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventcertificate_vertical_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, help_text='Kategori event (misal: Pelatihan, Seminar, dll)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Apakah event ini menyediakan sertifikat?'),
        ),
    ]
