# Generated by Django 5.2.12 on 2026-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_category_event_has_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='code_font_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='code_font_family',
            field=models.CharField(default='Roboto-Bold.ttf', max_length=100),
        ),
    ]
