# Generated by Django 5.2.12 on 2026-04-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventcertificate_code_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='link',
            field=models.URLField(blank=True, help_text='Link profil atau website narasumber', null=True),
        ),
    ]
