# Generated by Django 5.2.12 on 2026-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventspeaker_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_start_at',
            field=models.DateTimeField(blank=True, help_text='Waktu pendaftaran mulai dibuka (kosongkan jika langsung dibuka)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visible_at',
            field=models.DateTimeField(blank=True, help_text='Waktu event mulai ditampilkan di publik (kosongkan jika langsung tampil)', null=True),
        ),
    ]
