# Generated by Django 5.2.12 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_ots_payment',
            field=models.BooleanField(default=False, help_text='Izinkan pembayaran di tempat (On The Spot)'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('ots', 'On The Spot')], default='transfer', max_length=20),
        ),
    ]
