# Generated by Django 5.2.12 on 2026-05-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_allow_ots_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='events/bibs/templates/')),
                ('name_x', models.FloatField(default=50.0)),
                ('name_y', models.FloatField(default=85.0)),
                ('name_font_size', models.IntegerField(default=30)),
                ('name_font_color', models.CharField(default='#000000', max_length=7)),
                ('name_font_family', models.CharField(default='Roboto-Bold.ttf', max_length=100)),
                ('show_name', models.BooleanField(default=True)),
                ('number_x', models.FloatField(default=50.0)),
                ('number_y', models.FloatField(default=50.0)),
                ('number_font_size', models.IntegerField(default=150)),
                ('number_font_color', models.CharField(default='#000000', max_length=7)),
                ('number_font_family', models.CharField(default='Roboto-Bold.ttf', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bib', to='events.event')),
            ],
        ),
    ]
