# Generated by Django 5.2.12 on 2026-05-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventbib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbib',
            old_name='name_font_color',
            new_name='name_color',
        ),
        migrations.RenameField(
            model_name='eventbib',
            old_name='number_font_color',
            new_name='number_color',
        ),
        migrations.RemoveField(
            model_name='eventbib',
            name='name_font_family',
        ),
        migrations.RemoveField(
            model_name='eventbib',
            name='number_font_family',
        ),
        migrations.RemoveField(
            model_name='eventbib',
            name='show_name',
        ),
        migrations.AddField(
            model_name='eventbib',
            name='number_format',
            field=models.CharField(default='001', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='bib_number',
            field=models.PositiveIntegerField(blank=True, help_text='Nomor urut pendaftaran (untuk No Punggung/BIB)', null=True),
        ),
        migrations.AlterField(
            model_name='eventbib',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bib_template', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventbib',
            name='name_font_size',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='eventbib',
            name='name_y',
            field=models.FloatField(default=80.0),
        ),
    ]
