# Generated by Django 5.2.12 on 2026-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_name_font_color_eventbib_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_bib',
            field=models.BooleanField(default=False, help_text='Apakah event ini menyediakan nomor punggung (BIB)?'),
        ),
    ]
