# Generated by Django 5.2.12 on 2026-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_has_bib'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbib',
            name='name_font_family',
            field=models.CharField(default='Roboto-Bold.ttf', max_length=100),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='number_font_family',
            field=models.CharField(default='Roboto-Bold.ttf', max_length=100),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='photo_height',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='photo_width',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='photo_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='photo_y',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='eventbib',
            name='show_photo',
            field=models.BooleanField(default=False),
        ),
    ]
