# Generated by Django 5.1.6 on 2026-05-08 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_fix_eventbib_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='committees',
            field=models.ManyToManyField(blank=True, help_text='Panitia yang berhak melakukan scan kehadiran.', related_name='committee_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='bib_number',
            field=models.PositiveIntegerField(blank=True, help_text='Nomor urut pendaftaran (untuk No Peserta/BIB)', null=True),
        ),
    ]
