# Generated by Django 5.1.6 on 2026-05-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_is_automatic'),
        ('events', '0026_event_committees_alter_eventregistration_bib_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_for_labels',
            field=models.ManyToManyField(blank=True, help_text='Label user yang digratiskan pendaftarannya.', related_name='free_events', to='accounts.userlabel'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_special_qr',
            field=models.BooleanField(default=False, help_text='Apakah event ini menggunakan desain QR khusus?'),
        ),
        migrations.CreateModel(
            name='EventSpecialQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='events/special_qr/templates/')),
                ('code_type', models.CharField(choices=[('qr', 'QR Code'), ('barcode', 'Barcode')], default='qr', max_length=10)),
                ('code_x', models.FloatField(default=50.0)),
                ('code_y', models.FloatField(default=50.0)),
                ('code_width', models.FloatField(default=20.0)),
                ('code_height', models.FloatField(default=20.0)),
                ('field_layouts', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_qr_template', to='events.event')),
            ],
        ),
    ]
