# Generated by Django 5.1.6 on 2026-05-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_free_for_labels_event_has_special_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('internal', 'Internal Only (Hidden from Landing)'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EventPriceVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Misal: Paket Platinum, Early Bird, dll', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('benefits', models.TextField(blank=True, help_text='Keterangan benefit yang didapat (pisahkan dengan baris baru)', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_variations', to='events.event')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='price_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.eventpricevariation'),
        ),
    ]
