# Generated by Django 5.1.6 on 2026-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_status_eventpricevariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
