# Generated by Django 5.1.6 on 2026-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_order_completed',
            field=models.BooleanField(default=False, help_text='Tandai jika pesanan/form sudah diselesaikan (misal: makanan sudah diberikan)'),
        ),
    ]
