# Generated by Django 5.1.6 on 2026-05-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_eventregistration_is_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='committee_notes',
            field=models.TextField(blank=True, help_text='Catatan internal dari panitia untuk pendaftar ini', null=True),
        ),
    ]
