# Generated by Django 5.1.6 on 2026-05-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_eventregistration_committee_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nominal diskon dari voucher', max_digits=12),
        ),
        migrations.CreateModel(
            name='EventVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('percentage', 'Persentase (%)'), ('fixed', 'Nominal Tetap (Rp)')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quota', models.PositiveIntegerField(default=100, help_text='Jumlah maksimal voucher ini bisa digunakan')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='applied_voucher',
            field=models.ForeignKey(blank=True, help_text='Voucher yang digunakan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.eventvoucher'),
        ),
    ]
