# Generated by Django 5.1.6 on 2026-05-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventregistration_discount_amount_eventvoucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvoucher',
            name='apply_to_extras',
            field=models.BooleanField(default=False, help_text='Jika diskon %, apakah juga berlaku untuk tambahan harga dari form (opsi berbayar)?'),
        ),
    ]
