# Generated by Django 5.1.6 on 2026-05-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventvoucher_apply_to_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspecialqr',
            name='show_code',
            field=models.BooleanField(default=True, help_text='Tampilkan QR Code atau Barcode pada tiket'),
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Tim (Misal: Team A)', max_length=255)),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Kapasitas maksimal pendaftar untuk tim ini')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Bisa bernilai minus untuk diskon, atau plus untuk biaya tambahan', max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Pilihan tim peserta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.eventteam'),
        ),
    ]
