# Generated by Django 5.1.6 on 2026-06-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventspecialqr_show_code_eventteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Apakah event ini diadakan secara online (Zoom/GMeet/dll)?'),
        ),
    ]
