# Generated by Django 5.1.6 on 2026-06-12 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_likes'),
        ('events', '0036_event_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='charity',
            field=models.ForeignKey(blank=True, help_text='Program charity yang dipilih untuk kolaborasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_events', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='event',
            name='charity_charity_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nilai pembagian untuk program charity (dalam % atau nominal Rp)', max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='charity_operational_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nilai pembagian untuk operasional penyelenggara (dalam % atau nominal Rp)', max_digits=12),
        ),
        migrations.AddField(
            model_name='event',
            name='charity_split_mode',
            field=models.BooleanField(default=False, help_text='Bagi hasil pembayaran antara charity dan operasional'),
        ),
        migrations.AddField(
            model_name='event',
            name='charity_split_type',
            field=models.CharField(choices=[('percent', 'Persentase'), ('nominal', 'Nominal')], default='percent', help_text='Tipe pembagian hasil (persen atau nominal)', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='collab_charity',
            field=models.BooleanField(default=False, help_text='Aktifkan kolaborasi dengan program charity'),
        ),
    ]
