# Generated by Django 5.1.6 on 2026-06-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_event_charity_event_charity_charity_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blast_completed_message',
            field=models.TextField(blank=True, help_text='Template pesan WhatsApp blast saat event selesai.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_blasted_completed',
            field=models.BooleanField(default=False, help_text='Tandai jika blasting WhatsApp saat event selesai sudah dikirim.'),
        ),
        migrations.CreateModel(
            name='EventTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
