# Generated by Django 5.1.6 on 2026-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_event_blast_completed_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_post_to_activity',
            field=models.BooleanField(default=True, help_text='Otomatis posting ke kegiatan saat event selesai'),
        ),
    ]
