# Generated by Django 5.1.6 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_auto_post_to_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya Layanan & Admin / Kode Unik', max_digits=12),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('ots', 'On The Spot'), ('dynaqris', 'DynaQRIS Otomatis')], default='transfer', max_length=20),
        ),
    ]
