# Generated by Django 5.1.6 on 2026-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_eventregistration_admin_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='documentation_frame_1_1',
            field=models.ImageField(blank=True, help_text='Bingkai 1:1 format transparan (PNG/WebP) untuk otomatis overlay dokumentasi.', null=True, upload_to='events/frames/'),
        ),
    ]
